### ISSUE TITLE
readme on http://www.gisdoctor.com/leaflet/Add_Random_Map.html#

### ISSUE THREAD

**Issue by matkoniecz** [bspauld/RandomMaps#1]
http://www.gisdoctor.com/leaflet/Add_Random_Map.html# linked from readme has "Click on the "New Map" Button to View a New Random Map". 

The button has "Random Map" text, not "New Map".

**Comment by bspauld** [comment]
Updated "New Map" to "Random Map" 

Working example and code both updated.

Thanks
